WDL-OL/IPlug: IGraphicsMac Class Reference
IGraphicsMac Class Reference final
IGraphics::PlatformClasses
IGraphics platform class for macOS.
#include <IGraphicsMac.h>
Public Member Functions
IGraphicsMac (IPlugBaseGraphics &plug, int w, int h, int fps)
void SetBundleID (const char *bundleID)
void CreateMetalLayer ()
bool IsSandboxed ()
void * OpenWindow (void *pWindow) override
/todo <#Description#>
void CloseWindow () override
/todo <#Description#>
bool WindowIsOpen () override
/todo <#Description#>
void Resize (int w, int h, float scale) override
/todo <#Description#>
void SetTabletInput (bool tablet)
void HideMouseCursor () override
/todo <#Description#>
void ShowMouseCursor () override
/todo <#Description#>
int ShowMessageBox (const char *str, const char *caption, int type) override
/todo <#Description#>
void ForceEndUserEdit () override
/todo <#Description#>
const char * GetGUIAPI () override
/todo <#Description#>
void UpdateTooltips () override
/todo <#Description#>
void HostPath (WDL_String &path) override
/todo <#Description#>
void PluginPath (WDL_String &path) override
/todo <#Description#>
void DesktopPath (WDL_String &path) override
/todo <#Description#>
void UserHomePath (WDL_String &path) override
/todo <#Description#>
void AppSupportPath (WDL_String &path, bool isSystem) override
/todo <#Description#>
void SandboxSafeAppSupportPath (WDL_String &path) override
/todo <#Description#>
void VST3PresetsPath (WDL_String &path, bool isSystem) override
/todo <#Description#>
bool RevealPathInExplorerOrFinder (WDL_String &path, bool select) override
/todo <#Description#>
void PromptForFile (WDL_String &fileName, WDL_String &path, EFileAction action, const char *ext) override
/todo <#Description#>
bool PromptForColor (IColor &color, const char *str) override
/todo <#Description#>
IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, IRECT &rect) override
/todo <#Description#>
void CreateTextEntry (IControl *pControl, const IText &text, const IRECT &textRect, const char *str, IParam *pParam) override
/todo <#Description#>
bool OpenURL (const char *url, const char *msgWindowTitle, const char *confirmMsg, const char *errMsgOnFailure) override
/todo <#Description#>
void * GetWindow () override
/todo <#Description#>
const char * GetBundleID ()
bool GetTextFromClipboard (WDL_String &str) override
/todo <#Description#>
bool MeasureText (const IText &text, const char *str, IRECT &destRect) override
/todo <#Description#>
Public Member Functions inherited from IGraphicsLice
const char * GetDrawingAPIStr () override
/todo <#Description#>
IGraphicsLice (IPlugBaseGraphics &plug, int w, int h, int fps)
void SetDisplayScale (int) override
Called by platform IGraphics class when UI created and when moving to a new screen with different DPI, implementations in draw class must call the base implementation.
void DrawSVG (ISVG &svg, const IRECT &dest, const IBlend *pBlend) override
Draw an SVG image to the graphics context.
void DrawRotatedSVG (ISVG &svg, float destCtrX, float destCtrY, float width, float height, double angle, const IBlend *pBlend) override
/todo <#Description#>
void DrawBitmap (IBitmap &bitmap, const IRECT &dest, int srcX, int srcY, const IBlend *pBlend) override
/todo <#Description#>
void DrawRotatedBitmap (IBitmap &bitmap, int destCtrX, int destCtrY, double angle, int yOffsetZeroDeg, const IBlend *pBlend) override
/todo <#Description#>
void DrawRotatedMask (IBitmap &base, IBitmap &mask, IBitmap &top, int x, int y, double angle, const IBlend *pBlend) override
/todo <#Description#>
void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend) override
/todo <#Description#>
void ForcePixel (const IColor &color, int x, int y) override
/todo <#Description#>
void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend) override
/todo <#Description#>
void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
<#Description#>
void DrawRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
/todo <#Description#>
void DrawRoundRect (const IColor &color, const IRECT &rect, float cr, const IBlend *pBlend) override
/todo <#Description#>
void DrawConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend) override
/todo <#Description#>
void DrawArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend) override
/todo
void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
/todo <#Description#>
void DrawDottedRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
/todo <#Description#>
void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
/todo <#Description#>
void FillRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
/todo <#Description#>
void FillRoundRect (const IColor &color, const IRECT &rect, float cr, const IBlend *pBlend) override
/todo <#Description#>
void FillConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend) override
/todo <#Description#>
void FillArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend) override
/todo <#Description#>
void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
/todo <#Description#>
IColor GetPoint (int x, int y) override
/todo <#Description#>
void * GetData () override
/todo <#Description#>
bool DrawText (const IText &text, const char *str, IRECT &rect, bool measure) override
/todo <#Description#>
LICE_SysBitmap * GetDrawBitmap () const
Public Member Functions inherited from IGraphics
virtual void BeginFrame ()
virtual void EndFrame ()
virtual void ViewInitialized (void *layer)
virtual void ClipRegion (const IRECT &r)
/todo <#Description#>
virtual void ResetClipRegion ()
<#Description#>
virtual IBitmap LoadBitmap (const char *name, int nStates=1, bool framesAreHorizontal=false)
virtual IBitmap ScaleBitmap (const IBitmap &srcbitmap, const char *cacheName, int targetScale)
virtual void RetainBitmap (const IBitmap &bitmap, const char *cacheName)
virtual void ReleaseBitmap (const IBitmap &bitmap)
IBitmap GetScaledBitmap (IBitmap &src)
virtual void OnDisplayScale ()
<#Description#>
void DrawBitmap (IBitmap &bitmap, const IRECT &rect, int bmpState=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (IBitmap &bitmap, IRECT &rect, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws monospace bitmapped text.
void DrawVerticalLine (const IColor &color, const IRECT &rect, float x, const IBlend *pBlend=0)
/todo <#Description#>
void DrawHorizontalLine (const IColor &color, const IRECT &rect, float y, const IBlend *pBlend=0)
/todo <#Description#>
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0)
/todo <#Description#>
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0)
/todo <#Description#>
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0)
Helper function to draw a radial line, useful for pointers on dials.
void DrawGrid (const IColor &color, const IRECT &rect, int gridSizeH, int gridSizeV, const IBlend *pBlend)
/todo <#Description#>
virtual void SetPlatformInstance (void *pInstance)
virtual void * GetPlatformInstance ()
/todo <#Description#>
virtual void SetPlatformContext (void *pContext)
Used with IGraphicsLice (possibly others) in order to set the core graphics draw context on macOS and the GDI HDC draw context handle on Windows On macOS, this is called by the platform IGraphics class IGraphicsMac, on Windows it is called by the drawing class e.g.
void * GetPlatformContext ()
/todo <#Description#>
IGraphics (IPlugBaseGraphics &plug, int w, int h, int fps=0)
bool IsDirty (IRECT &rect)
/todo <#Description#>
virtual void Draw (const IRECT &rect)
/todo <#Description#>
virtual ISVG LoadSVG (const char *name)
/todo <#Description#>
void PromptUserInput (IControl *pControl, IParam *pParam, IRECT &textRect)
/todo <#Description#>
void SetFromStringAfterPrompt (IControl *pControl, IParam *pParam, const char *txt)
/todo <#Description#>
IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, float x, float y)
/todo <#Description#>
void SetStrictDrawing (bool strict)
/todo <#Description#>
int Width () const
/todo <#Description#>
int Height () const
/todo <#Description#>
int WindowWidth () const
/todo <#Description#>
int WindowHeight () const
/todo <#Description#>
int FPS () const
/todo <#Description#>
float GetScale () const
/todo <#Description#>
float GetDisplayScale () const
/todo <#Description#>
IPlugBaseGraphics & GetPlug ()
/todo <#Description#>
void AttachBackground (const char *name)
void AttachPanelBackground (const IColor &color)
void AttachKeyCatcher (IControl &control)
int AttachControl (IControl *pControl)
/todo <#Description#>
IControl * GetControl (int idx)
/todo <#Description#>
int NControls () const
/todo <#Description#>
void HideControl (int paramIdx, bool hide)
/todo <#Description#>
void GrayOutControl (int paramIdx, bool gray)
/todo <#Description#>
void ClampControl (int paramIdx, double lo, double hi, bool normalized)
/todo <#Description#>
void SetAllControlsDirty ()
/todo <#Description#>
void SetControlFromPlug (int controlIdx, double normalizedValue)
/todo <#Description#>
void SetParameterFromPlug (int paramIdx, double value, bool normalized)
/todo <#Description#>
void SetParameterFromGUI (int paramIdx, double normalizedValue)
/todo <#Description#>
void OnMouseDown (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseUp (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
/todo <#Description#>
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
/todo <#Description#>
bool OnKeyDown (float x, float y, int key)
/todo <#Description#>
bool OnMouseOver (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseOut ()
/todo <#Description#>
void OnDrop (const char *str, float x, float y)
/todo <#Description#>
void OnGUIIdle ()
/todo <#Description#>
int GetParamIdxForPTAutomation (float x, float y)
[AAX only]
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily]
void HandleMouseOver (bool canHandle)
/todo <#Description#>
void ReleaseMouseCapture ()
/todo <#Description#>
void EnableTooltips (bool enable)
/todo <#Description#>
void AssignParamNameToolTips ()
/todo <#Description#>
void ShowControlBounds (bool enable)
/todo <#Description#>
void ShowAreaDrawn (bool enable)
/todo <#Description#>
void EnableLiveEdit (bool enable, const char *file=0, int gridsize=10)
/todo <#Description#>
IRECT GetDrawRect () const
/todo Get the area marked for drawing
IRECT GetBounds () const
Get an IRECT that represents the entire UI bounds.
bool CanHandleMouseOver () const
/todo <#Description#>
int GetMouseOver () const
/todo <#Description#>
bool TooltipsEnabled () const
/todo <#Description#>
virtual void LoadFont (const char *name)
/todo <#Description#>
Static Public Member Functions
static int GetUserOSVersion ()
Public Attributes
void * mLayer
Protected Member Functions
bool OSFindResource (const char *name, const char *type, WDL_String &result) override
Try to ascertain the full path of a resource.
Protected Member Functions inherited from IGraphicsLice
APIBitmap * LoadAPIBitmap (const WDL_String &resourcePath, int scale) override
APIBitmap * ScaleAPIBitmap (const APIBitmap *pBitmap, int scale) override
void RenderDrawBitmap () override
Called by some drawing API classes to finally blit the draw bitmap onto the screen.
Protected Member Functions inherited from IGraphics
void SearchNextScale (int &sourceScale, int targetScale)
bool SearchImageResource (const char *name, const char *type, WDL_String &result, int targetScale, int &sourceScale)
APIBitmap * SearchBitmapInCache (const char *name, int targetScale, int &sourceScale)
Friends
int GetMouseOver (IGraphicsMac *pGraphics)
Additional Inherited Members
Protected Attributes inherited from IGraphics
IPlugBaseGraphics & mPlug
WDL_PtrList< IControl > mControls
IRECT mDrawRECT
void * mPlatformContext = nullptr
bool mCursorHidden = false
FT_Library mFTLibrary = nullptr
FT_Face mFTFace = nullptr
Detailed Description
IGraphics platform class for macOS.
Definition at line 22 of file IGraphicsMac.h.
Member Function Documentation
void IGraphicsMac::AppSupportPath (WDL_String & path, bool isSystem) override virtual
/todo <#Description#>
Parameters
path <#path description#>
isSystem <#isSystem description#>
Implements IGraphics.
Definition at line 386 of file IGraphicsMac.mm.
IPopupMenu * IGraphicsMac::CreateIPopupMenu (IPopupMenu & menu, IRECT & textRect) override virtual
/todo <#Description#>
Parameters
menu <#menu description#>
textRect <#textRect description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 525 of file IGraphicsMac.mm.
References IGraphics::ReleaseMouseCapture().
void IGraphicsMac::CreateTextEntry (IControl * pControl, const IText & text, const IRECT & textRect, const char * str, IParam * pParam) override virtual
/todo <#Description#>
Parameters
pControl <#pControl description#>
text <#text description#>
textRect <#textRect description#>
"" <#"" description#>
pParam <#pParam description#>
Implements IGraphics.
Definition at line 537 of file IGraphicsMac.mm.
void IGraphicsMac::DesktopPath (WDL_String & path) override virtual
/todo <#Description#>
Parameters
path <#path description#>
Implements IGraphics.
Definition at line 361 of file IGraphicsMac.mm.
Referenced by PromptForFile().
const char * IGraphicsMac::GetGUIAPI () override virtual
/todo <#Description#>
Returns
<#return value description#>
Reimplemented from IGraphics.
Definition at line 324 of file IGraphicsMac.mm.
bool IGraphicsMac::GetTextFromClipboard (WDL_String & str) override virtual
/todo <#Description#>
Parameters
str <#str description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 579 of file IGraphicsMac.mm.
void IGraphicsMac::HostPath (WDL_String & path) override virtual
/todo <#Description#>
Parameters
path <#path description#>
Implements IGraphics.
Definition at line 329 of file IGraphicsMac.mm.
bool IGraphicsMac::MeasureText (const IText & text, const char * str, IRECT & destRect) override virtual
/todo <#Description#>
Parameters
text <#text description#>
str <#str description#>
destRect <#destRect description#>
Returns
<#return value description#>
Reimplemented from IGraphicsLice.
Definition at line 156 of file IGraphicsMac.mm.
References IGraphicsLice::MeasureText().
bool IGraphicsMac::OpenURL (const char * url, const char * msgWindowTitle, const char * confirmMsg, const char * errMsgOnFailure) override virtual
/todo <#Description#>
Parameters
url <#url description#>
msgWindowTitle <#msgWindowTitle description#>
confirmMsg <#confirmMsg description#>
errMsgOnFailure <#errMsgOnFailure description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 546 of file IGraphicsMac.mm.
void * IGraphicsMac::OpenWindow (void * pParentWnd) override virtual
/todo <#Description#>
Parameters
pParentWnd <#pParentWnd description#>
Implements IGraphics.
Definition at line 163 of file IGraphicsMac.mm.
References CloseWindow(), and UpdateTooltips().
bool IGraphicsMac::OSFindResource (const char * name, const char * type, WDL_String & result) override protected virtual
Try to ascertain the full path of a resource.
Parameters
name <#name description#>
type <#type description#>
result <#result description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 128 of file IGraphicsMac.mm.
void IGraphicsMac::PluginPath (WDL_String & path) override virtual
/todo <#Description#>
Parameters
path <#path description#>
Implements IGraphics.
Definition at line 344 of file IGraphicsMac.mm.
bool IGraphicsMac::PromptForColor (IColor & color, const char * str) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
"" <#"" description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 519 of file IGraphicsMac.mm.
void IGraphicsMac::PromptForFile (WDL_String & filename, WDL_String & path, EFileAction action, const char * extensions) override virtual
/todo <#Description#>
Parameters
filename <#filename description#>
path <#path description#>
action <#action description#>
extensions <#extensions description#>
Implements IGraphics.
Definition at line 440 of file IGraphicsMac.mm.
References DesktopPath(), and WindowIsOpen().
void IGraphicsMac::Resize (int w, int h, float scale) override virtual
/todo <#Description#>
Parameters
w <#w description#>
h <#h description#>
scale <#scale description#>
Reimplemented from IGraphics.
Definition at line 200 of file IGraphicsMac.mm.
References IGraphics::GetScale(), IGraphics::Height(), IGraphics::Resize(), and IGraphics::Width().
bool IGraphicsMac::RevealPathInExplorerOrFinder (WDL_String & path, bool select) override virtual
/todo <#Description#>
Parameters
path <#path description#>
select <#select description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 406 of file IGraphicsMac.mm.
void IGraphicsMac::SandboxSafeAppSupportPath (WDL_String & path) override virtual
/todo <#Description#>
Parameters
path <#path description#>
Implements IGraphics.
Definition at line 399 of file IGraphicsMac.mm.
int IGraphicsMac::ShowMessageBox (const char * str, const char * caption, int type) override virtual
/todo <#Description#>
Parameters
str <#str description#>
caption <#caption description#>
type <#type description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 232 of file IGraphicsMac.mm.
void IGraphicsMac::UserHomePath (WDL_String & path) override virtual
/todo <#Description#>
Parameters
path <#path description#>
Implements IGraphics.
Definition at line 368 of file IGraphicsMac.mm.
void IGraphicsMac::VST3PresetsPath (WDL_String & path, bool isSystem) override virtual
/todo <#Description#>
Parameters
path <#path description#>
isSystem <#isSystem description#>
Reimplemented from IGraphics.
Definition at line 374 of file IGraphicsMac.mm.
References IPlugBase::GetMfrName().
bool IGraphicsMac::WindowIsOpen () override virtual
/todo <#Description#>
Returns
<#return value description#>
Reimplemented from IGraphics.
Definition at line 195 of file IGraphicsMac.mm.
Referenced by PromptForFile().
The documentation for this class was generated from the following files:
IGraphicsMac.h
IGraphicsMac.mm