WDL-OL/IPlug: IGraphicsNanoVG Class Reference
IGraphicsNanoVG Class Reference
IGraphics::DrawClasses
IGraphics draw class using NanoVG.
#include <IGraphicsNanoVG.h>
Public Member Functions
const char * GetDrawingAPIStr () override
/todo <#Description#>
IGraphicsNanoVG (IPlugBaseGraphics &plug, int w, int h, int fps)
void BeginFrame () override
void EndFrame () override
void ViewInitialized (void *layer) override
void DrawSVG (ISVG &svg, const IRECT &dest, const IBlend *pBlend) override
Draw an SVG image to the graphics context.
void DrawRotatedSVG (ISVG &svg, float destCtrX, float destCtrY, float width, float height, double angle, const IBlend *pBlend) override
/todo <#Description#>
void DrawBitmap (IBitmap &bitmap, const IRECT &dest, int srcX, int srcY, const IBlend *pBlend) override
/todo <#Description#>
void DrawRotatedBitmap (IBitmap &bitmap, int destCtrX, int destCtrY, double angle, int yOffsetZeroDeg, const IBlend *pBlend) override
/todo <#Description#>
void DrawRotatedMask (IBitmap &base, IBitmap &mask, IBitmap &top, int x, int y, double angle, const IBlend *pBlend) override
/todo <#Description#>
void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend) override
/todo <#Description#>
void ForcePixel (const IColor &color, int x, int y) override
/todo <#Description#>
void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend) override
/todo <#Description#>
void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
<#Description#>
void DrawRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
/todo <#Description#>
void DrawRoundRect (const IColor &color, const IRECT &rect, float cr, const IBlend *pBlend) override
/todo <#Description#>
void DrawConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend=0) override
/todo <#Description#>
void DrawArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend) override
/todo
void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
/todo <#Description#>
void DrawDottedRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
/todo <#Description#>
void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
/todo <#Description#>
void FillRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
/todo <#Description#>
void FillRoundRect (const IColor &color, const IRECT &rect, float cr, const IBlend *pBlend) override
/todo <#Description#>
void FillConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend) override
/todo <#Description#>
void FillArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend) override
/todo <#Description#>
void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
/todo <#Description#>
IColor GetPoint (int x, int y) override
/todo <#Description#>
void * GetData () override
/todo <#Description#>
bool DrawText (const IText &text, const char *str, IRECT &rect, bool measure) override
/todo <#Description#>
bool MeasureText (const IText &text, const char *str, IRECT &destRect) override
/todo <#Description#>
IBitmap LoadBitmap (const char *name, int nStates, bool framesAreHorizontal) override
IBitmap ScaleBitmap (const IBitmap &bitmap, const char *name, int targetScale) override
void RetainBitmap (const IBitmap &bitmap, const char *cacheName) override
Public Member Functions inherited from IGraphics
virtual void SetDisplayScale (int scale)
Called by platform IGraphics class when UI created and when moving to a new screen with different DPI, implementations in draw class must call the base implementation.
virtual void ClipRegion (const IRECT &r)
/todo <#Description#>
virtual void ResetClipRegion ()
<#Description#>
virtual void ReleaseBitmap (const IBitmap &bitmap)
IBitmap GetScaledBitmap (IBitmap &src)
virtual void OnDisplayScale ()
<#Description#>
virtual void RenderDrawBitmap ()
Called by some drawing API classes to finally blit the draw bitmap onto the screen.
void DrawBitmap (IBitmap &bitmap, const IRECT &rect, int bmpState=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (IBitmap &bitmap, IRECT &rect, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws monospace bitmapped text.
void DrawVerticalLine (const IColor &color, const IRECT &rect, float x, const IBlend *pBlend=0)
/todo <#Description#>
void DrawHorizontalLine (const IColor &color, const IRECT &rect, float y, const IBlend *pBlend=0)
/todo <#Description#>
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0)
/todo <#Description#>
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0)
/todo <#Description#>
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0)
Helper function to draw a radial line, useful for pointers on dials.
void DrawGrid (const IColor &color, const IRECT &rect, int gridSizeH, int gridSizeV, const IBlend *pBlend)
/todo <#Description#>
virtual void HideMouseCursor ()
/todo <#Description#>
virtual void ShowMouseCursor ()
/todo <#Description#>
virtual void ForceEndUserEdit ()=0
/todo <#Description#>
virtual void Resize (int w, int h, float scale)
/todo <#Description#>
virtual void * OpenWindow (void *pParentWnd)=0
/todo <#Description#>
virtual void CloseWindow ()=0
/todo <#Description#>
virtual void * GetWindow ()=0
/todo <#Description#>
virtual bool GetTextFromClipboard (WDL_String &str)=0
/todo <#Description#>
virtual void UpdateTooltips ()=0
/todo <#Description#>
virtual int ShowMessageBox (const char *str, const char *caption, int type)=0
/todo <#Description#>
virtual IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, IRECT &textRect)=0
/todo <#Description#>
virtual void CreateTextEntry (IControl *pControl, const IText &text, const IRECT &textRect, const char *str="", IParam *pParam=0)=0
/todo <#Description#>
virtual void PromptForFile (WDL_String &filename, WDL_String &path, EFileAction action=kFileOpen, const char *extensions=0)=0
/todo <#Description#>
virtual bool PromptForColor (IColor &color, const char *str="")=0
/todo <#Description#>
virtual bool OpenURL (const char *url, const char *msgWindowTitle=0, const char *confirmMsg=0, const char *errMsgOnFailure=0)=0
/todo <#Description#>
virtual const char * GetGUIAPI ()
/todo <#Description#>
virtual bool WindowIsOpen ()
/todo <#Description#>
virtual void HostPath (WDL_String &path)=0
/todo <#Description#>
virtual void PluginPath (WDL_String &path)=0
/todo <#Description#>
virtual void DesktopPath (WDL_String &path)=0
/todo <#Description#>
virtual void UserHomePath (WDL_String &path)=0
/todo <#Description#>
virtual void AppSupportPath (WDL_String &path, bool isSystem=false)=0
/todo <#Description#>
virtual void SandboxSafeAppSupportPath (WDL_String &path)=0
/todo <#Description#>
virtual void VST3PresetsPath (WDL_String &path, bool isSystem=true)
/todo <#Description#>
virtual bool RevealPathInExplorerOrFinder (WDL_String &path, bool select=false)=0
/todo <#Description#>
virtual void SetPlatformInstance (void *pInstance)
virtual void * GetPlatformInstance ()
/todo <#Description#>
virtual void SetPlatformContext (void *pContext)
Used with IGraphicsLice (possibly others) in order to set the core graphics draw context on macOS and the GDI HDC draw context handle on Windows On macOS, this is called by the platform IGraphics class IGraphicsMac, on Windows it is called by the drawing class e.g.
void * GetPlatformContext ()
/todo <#Description#>
virtual bool OSFindResource (const char *name, const char *type, WDL_String &result)=0
Try to ascertain the full path of a resource.
IGraphics (IPlugBaseGraphics &plug, int w, int h, int fps=0)
bool IsDirty (IRECT &rect)
/todo <#Description#>
virtual void Draw (const IRECT &rect)
/todo <#Description#>
virtual ISVG LoadSVG (const char *name)
/todo <#Description#>
void PromptUserInput (IControl *pControl, IParam *pParam, IRECT &textRect)
/todo <#Description#>
void SetFromStringAfterPrompt (IControl *pControl, IParam *pParam, const char *txt)
/todo <#Description#>
IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, float x, float y)
/todo <#Description#>
void SetStrictDrawing (bool strict)
/todo <#Description#>
int Width () const
/todo <#Description#>
int Height () const
/todo <#Description#>
int WindowWidth () const
/todo <#Description#>
int WindowHeight () const
/todo <#Description#>
int FPS () const
/todo <#Description#>
float GetScale () const
/todo <#Description#>
float GetDisplayScale () const
/todo <#Description#>
IPlugBaseGraphics & GetPlug ()
/todo <#Description#>
void AttachBackground (const char *name)
void AttachPanelBackground (const IColor &color)
void AttachKeyCatcher (IControl &control)
int AttachControl (IControl *pControl)
/todo <#Description#>
IControl * GetControl (int idx)
/todo <#Description#>
int NControls () const
/todo <#Description#>
void HideControl (int paramIdx, bool hide)
/todo <#Description#>
void GrayOutControl (int paramIdx, bool gray)
/todo <#Description#>
void ClampControl (int paramIdx, double lo, double hi, bool normalized)
/todo <#Description#>
void SetAllControlsDirty ()
/todo <#Description#>
void SetControlFromPlug (int controlIdx, double normalizedValue)
/todo <#Description#>
void SetParameterFromPlug (int paramIdx, double value, bool normalized)
/todo <#Description#>
void SetParameterFromGUI (int paramIdx, double normalizedValue)
/todo <#Description#>
void OnMouseDown (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseUp (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
/todo <#Description#>
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
/todo <#Description#>
bool OnKeyDown (float x, float y, int key)
/todo <#Description#>
bool OnMouseOver (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseOut ()
/todo <#Description#>
void OnDrop (const char *str, float x, float y)
/todo <#Description#>
void OnGUIIdle ()
/todo <#Description#>
int GetParamIdxForPTAutomation (float x, float y)
[AAX only]
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily]
void HandleMouseOver (bool canHandle)
/todo <#Description#>
void ReleaseMouseCapture ()
/todo <#Description#>
void EnableTooltips (bool enable)
/todo <#Description#>
void AssignParamNameToolTips ()
/todo <#Description#>
void ShowControlBounds (bool enable)
/todo <#Description#>
void ShowAreaDrawn (bool enable)
/todo <#Description#>
void EnableLiveEdit (bool enable, const char *file=0, int gridsize=10)
/todo <#Description#>
IRECT GetDrawRect () const
/todo Get the area marked for drawing
IRECT GetBounds () const
Get an IRECT that represents the entire UI bounds.
bool CanHandleMouseOver () const
/todo <#Description#>
int GetMouseOver () const
/todo <#Description#>
bool TooltipsEnabled () const
/todo <#Description#>
virtual void LoadFont (const char *name)
/todo <#Description#>
Protected Member Functions
APIBitmap * LoadAPIBitmap (const WDL_String &resourcePath, int scale) override
APIBitmap * ScaleAPIBitmap (const APIBitmap *pBitmap, int scale) override
void Stroke (const IColor &color, const IBlend *pBlend=0)
void Fill (const IColor &color, const IBlend *pBlend=0)
void NVGDrawTriangle (float x1, float y1, float x2, float y2, float x3, float y3)
void NVGDrawConvexPolygon (float *x, float *y, int npoints)
Protected Member Functions inherited from IGraphics
void SearchNextScale (int &sourceScale, int targetScale)
bool SearchImageResource (const char *name, const char *type, WDL_String &result, int targetScale, int &sourceScale)
APIBitmap * SearchBitmapInCache (const char *name, int targetScale, int &sourceScale)
Protected Attributes
WDL_PtrList< NanoVGBitmap > mBitmaps
NVGcontext * mVG = nullptr
Protected Attributes inherited from IGraphics
IPlugBaseGraphics & mPlug
WDL_PtrList< IControl > mControls
IRECT mDrawRECT
void * mPlatformContext = nullptr
bool mCursorHidden = false
FT_Library mFTLibrary = nullptr
FT_Face mFTFace = nullptr
Detailed Description
IGraphics draw class using NanoVG.
Definition at line 57 of file IGraphicsNanoVG.h.
Member Function Documentation
void IGraphicsNanoVG::DrawArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend) override virtual
/todo
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
aMin the start angle of the arc at in degrees clockwise where 0 is up /see IGraphicsDrawing documentation
aMax the end angle of the arc at in degrees clockwise where 0 is up /see IGraphicsDrawing documentation
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 217 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::DrawBitmap (IBitmap & bitmap, const IRECT & rect, int srcX, int srcY, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
bitmap The bitmap image to draw to the graphics context
rect The rectangular area to draw the image in
srcX <#srcX description#>
srcY <#srcY description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 122 of file IGraphicsNanoVG.cpp.
References IBitmap::GetAPIBitmap(), IBitmap::H(), and IBitmap::W().
void IGraphicsNanoVG::DrawCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 224 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::DrawConvexPolygon (const IColor & color, float * x, float * y, int npoints, const IBlend * pBlend = 0) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
npoints <#npoints description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 211 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::DrawDottedRect (const IColor & color, const IRECT & rect, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 165 of file IGraphicsNanoVG.cpp.
References DrawRect().
void IGraphicsNanoVG::DrawLine (const IColor & color, float x1, float y1, float x2, float y2, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x1 <#x1 description#>
y1 <#y1 description#>
x2 <#x2 description#>
y2 <#y2 description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 183 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::DrawPoint (const IColor & color, float x, float y, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 171 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::DrawRect (const IColor & color, const IRECT & rect, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 197 of file IGraphicsNanoVG.cpp.
Referenced by DrawDottedRect().
void IGraphicsNanoVG::DrawRotatedBitmap (IBitmap & bitmap, int destCentreX, int destCentreY, double angle, int yOffsetZeroDeg, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
bitmap The bitmap image to draw to the graphics context
destCentreX The X coordinate of the centre point at which to rotate the image around. /todo check this
destCentreY The Y coordinate of the centre point at which to rotate the image around. /todo check this
angle The angle of rotation in degrees
yOffsetZeroDeg /todo
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 132 of file IGraphicsNanoVG.cpp.
References IBitmap::GetAPIBitmap(), IBitmap::H(), and IBitmap::W().
void IGraphicsNanoVG::DrawRotatedMask (IBitmap & base, IBitmap & mask, IBitmap & top, int x, int y, double angle, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
angle the angle to rotate the bitmap mask at in degrees clockwise /see IGraphicsDrawing documentation
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 142 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::DrawRotatedSVG (ISVG & svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
svg The svg image to draw to the graphics context
destCentreX The X coordinate of the centre point at which to rotate the image around. /todo check this
destCentreY The Y coordinate of the centre point at which to rotate the image around. /todo check this
width /todo
height /todo
angle angle the angle to rotate the bitmap mask at in degrees clockwise /see IGraphicsDrawing documentation
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 113 of file IGraphicsNanoVG.cpp.
References DrawSVG().
void IGraphicsNanoVG::DrawRoundRect (const IColor & color, const IRECT & rect, float cr, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
.f <#.f description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 204 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::DrawSVG (ISVG & svg, const IRECT & rect, const IBlend * pBlend) override virtual
Draw an SVG image to the graphics context.
Parameters
svg The image to draw
rect The rectangular area to draw the image in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 97 of file IGraphicsNanoVG.cpp.
Referenced by DrawRotatedSVG().
bool IGraphicsNanoVG::DrawText (const IText & text, const char * str, IRECT & destRect, bool measure) override virtual
/todo <#Description#>
Parameters
text <#text description#>
str <#str description#>
destRect <#destRect description#>
measure <#measure description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 278 of file IGraphicsNanoVG.cpp.
Referenced by MeasureText().
void IGraphicsNanoVG::DrawTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend) override virtual
<#Description#>
Parameters
color <#color description#>
x1 <#x1 description#>
y1 <#y1 description#>
x2 <#x2 description#>
y2 <#y2 description#>
x3 <#x3 description#>
y3 <#y3 description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 191 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::FillArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
aMin <#aMin description#>
aMax <#aMax description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 257 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::FillCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 266 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::FillConvexPolygon (const IColor & color, float * x, float * y, int npoints, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
npoints <#npoints description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 251 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::FillRect (const IColor & color, const IRECT & rect, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 237 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::FillRoundRect (const IColor & color, const IRECT & rect, float cr, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
.f <#.f description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 244 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::FillTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x1 <#x1 description#>
y1 <#y1 description#>
x2 <#x2 description#>
y2 <#y2 description#>
x3 <#x3 description#>
y3 <#y3 description#>
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 231 of file IGraphicsNanoVG.cpp.
void IGraphicsNanoVG::ForcePixel (const IColor & color, int x, int y) override virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
Implements IGraphics.
Definition at line 178 of file IGraphicsNanoVG.cpp.
const char* IGraphicsNanoVG::GetDrawingAPIStr () inline override virtual
/todo <#Description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 60 of file IGraphicsNanoVG.h.
IColor IGraphicsNanoVG::GetPoint (int x, int y) override virtual
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 273 of file IGraphicsNanoVG.cpp.
bool IGraphicsNanoVG::MeasureText (const IText & text, const char * str, IRECT & destRect) override virtual
/todo <#Description#>
Parameters
text <#text description#>
str <#str description#>
destRect <#destRect description#>
Returns
<#return value description#>
Implements IGraphics.
Definition at line 283 of file IGraphicsNanoVG.cpp.
References DrawText().
The documentation for this class was generated from the following files:
IGraphicsNanoVG.h
IGraphicsNanoVG.cpp