WDL-OL/IPlug: IPlugProcessor< sampleType > Class Template Reference
IPlugProcessor< sampleType > Class Template Reference abstract
The base class for IPlug Audio Processing.
#include <IPlugProcessor.h>
Public Member Functions
IPlugProcessor (IPlugConfig config, EAPI plugAPI)
virtual void ProcessBlock (sampleType **inputs, sampleType **outputs, int nFrames)
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
virtual void ProcessMidiMsg (const IMidiMsg &msg)
Override this method which is called prior to ProcessBlock(), to handle incoming MIDI messages.
virtual void ProcessSysEx (ISysEx &msg)
Override this method which is calledThis method is called prior to ProcessBlock(), to handle incoming MIDI System Exclusive (SysEx) messages.
virtual void OnReset ()
Override this method in your plug-in class to do something prior to playback etc.
virtual void OnActivate (bool active)
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
virtual void OnIdle ()
Override this method to get an "idle"" call from the audio processing thread in VST2 plug-ins.
virtual bool SendMidiMsg (const IMidiMsg &msg)=0
Send a single MIDI message.
bool SendMidiMsgs (WDL_TypedBuf< IMidiMsg > &msgs)
Send a collection of MIDI messages.
virtual bool SendSysEx (ISysEx &msg)
Send a single MIDI System Exclusive (SysEx) message.
double GetSampleRate () const
int GetBlockSize () const
int GetLatency () const
int GetTailSize ()
bool GetBypassed () const
bool GetRenderingOffline () const
int GetSamplePos () const
double GetTempo () const
double GetSamplesPerBeat () const
void GetTimeSig (int &numerator, int &denominator)
int MaxNBuses (ERoute direction) const
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
int MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
bool HasWildcardBus (ERoute direction) const
Check if we have any wildcard characters in the channel io configs.
int NIOConfigs () const
IOConfig * GetIOConfig (int idx)
int NInChannels () const
int NOutChannels () const
bool IsInChannelConnected (int chIdx) const
bool IsOutChannelConnected (int chIdx) const
int NInChansConnected () const
int NOutChansConnected () const
bool LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
bool HasSidechainInput () const
int NSidechainChannels () const
void LimitToStereoIO ()
This is called by IPlugVST in order to limit a plug-in to stereo I/O for certain picky hosts /todo may no longer be relevant.
bool IsInstrument () const
bool DoesMIDI () const
void SetInputLabel (int idx, const char *label)
This allows you to label input channels in supporting VST2 hosts.
void SetOutputLabel (int idx, const char *label)
This allows you to label output channels in supporting VST2 hosts.
virtual void SetLatency (int latency)
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
void SetTailSize (int tailSize)
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
void SetSampleRate (double sampleRate)
void SetBlockSize (int blockSize)
void SetBypassed (bool bypassed)
void SetTimeInfo (const ITimeInfo &timeInfo)
void SetRenderingOffline (bool renderingOffline)
const WDL_String & GetInputLabel (int idx)
const WDL_String & GetOutputLabel (int idx)
Static Public Member Functions
static int ParseChannelIOStr (const char *IOStr, WDL_PtrList< IOConfig > &channelIOList, int &totalNInChans, int &totalNOutChans, int &totalNInBuses, int &totalNOutBuses)
A static method to parse the config.h channel I/O string.
Protected Member Functions
void SetInputChannelConnections (int idx, int n, bool connected)
void SetOutputChannelConnections (int idx, int n, bool connected)
void AttachInputBuffers (int idx, int n, PLUG_SAMPLE_DST **ppData, int nFrames)
void AttachInputBuffers (int idx, int n, PLUG_SAMPLE_SRC **ppData, int nFrames)
void AttachOutputBuffers (int idx, int n, PLUG_SAMPLE_DST **ppData)
void AttachOutputBuffers (int idx, int n, PLUG_SAMPLE_SRC **ppData)
void PassThroughBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void PassThroughBuffers (PLUG_SAMPLE_DST type, int nFrames)
void ProcessBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void ProcessBuffers (PLUG_SAMPLE_DST type, int nFrames)
void ProcessBuffersAccumulating (PLUG_SAMPLE_SRC type, int nFrames)
void ZeroScratchBuffers ()
Protected Attributes
NChanDelayLine< sampleType > * mLatencyDelay = nullptr
Pointer to a multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
Detailed Description
template<typename sampleType>
class IPlugProcessor< sampleType >
The base class for IPlug Audio Processing.
It knows nothing about presets or parameters or user interface.
Definition at line 24 of file IPlugProcessor.h.
Member Function Documentation
template<typename sampleType> int IPlugProcessor< sampleType >::GetBlockSize () const inline
Returns
Current block size in samples
Definition at line 86 of file IPlugProcessor.h.
template<typename sampleType> bool IPlugProcessor< sampleType >::GetBypassed () const inline
Returns
True if the plugin is currently bypassed
Definition at line 95 of file IPlugProcessor.h.
template<typename sampleType> IOConfig* IPlugProcessor< sampleType >::GetIOConfig (int idx) inline
Returns
Pointer to an IOConfig at idx. Can return nullptr if idx is invalid
Definition at line 135 of file IPlugProcessor.h.
template<typename sampleType> int IPlugProcessor< sampleType >::GetLatency () const inline
Returns
Plugin latency (in samples)
Definition at line 89 of file IPlugProcessor.h.
template<typename sampleType> bool IPlugProcessor< sampleType >::GetRenderingOffline () const inline
Returns
True if the plugin is currently rendering off-line
Definition at line 98 of file IPlugProcessor.h.
template<typename sampleType> int IPlugProcessor< sampleType >::GetSamplePos () const inline
Returns
The number of samples elapsed since start of project timeline.
Definition at line 102 of file IPlugProcessor.h.
template<typename sampleType> double IPlugProcessor< sampleType >::GetSampleRate () const inline
Returns
Sample rate (in Hz)
Definition at line 83 of file IPlugProcessor.h.
template<typename sampleType > double IPlugProcessor< sampleType >::GetSamplesPerBeat () const
Returns
The Tempo in beats per minute
Definition at line 102 of file IPlugProcessor.cpp.
template<typename sampleType> int IPlugProcessor< sampleType >::GetTailSize () inline
Returns
The tail size in samples (useful for reverberation plug-ins, that may need to decay after the transport stops or an audio item ends)
Definition at line 92 of file IPlugProcessor.h.
template<typename sampleType> double IPlugProcessor< sampleType >::GetTempo () const inline
Returns
The Tempo in beats per minute
Definition at line 105 of file IPlugProcessor.h.
template<typename sampleType> void IPlugProcessor< sampleType >::GetTimeSig (int & numerator, int & denominator) inline
Parameters
numerator The upper part of the current time signature e.g "6" in the time signature 6/8
denominator The lower part of the current time signature e.g "8" in the time signature 6/8
Definition at line 112 of file IPlugProcessor.h.
template<typename sampleType> bool IPlugProcessor< sampleType >::HasSidechainInput () const inline
Returns
c/ true if this plug-in has a side-chain input, which may not necessarily be active in the current io config
Definition at line 164 of file IPlugProcessor.h.
template<typename sampleType> bool IPlugProcessor< sampleType >::HasWildcardBus (ERoute direction) const inline
Check if we have any wildcard characters in the channel io configs.
Parameters
direction Return input or output bus count
Returns
/true if the bus has a wildcard, meaning it should work on any number of channels
Definition at line 129 of file IPlugProcessor.h.
template<typename sampleType > bool IPlugProcessor< sampleType >::IsInChannelConnected (int chIdx) const
Parameters
chIdx channel index
Returns
/c true if the host has connected this input channel
Definition at line 135 of file IPlugProcessor.cpp.
template<typename sampleType > bool IPlugProcessor< sampleType >::IsOutChannelConnected (int chIdx) const
Parameters
chIdx channel index
Returns
/c true if the host has connected this output channel
Definition at line 141 of file IPlugProcessor.cpp.
template<typename sampleType > bool IPlugProcessor< sampleType >::LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
Parameters
NInputChans Number of inputs to test, if set to -1 = check NOutputChans only
NOutputChans Number of outputs to test, if set to -1 = check NInputChans only
Returns
/c true if the configurations is valid
Definition at line 171 of file IPlugProcessor.cpp.
References IOConfig::GetTotalNChannels().
template<typename sampleType> int IPlugProcessor< sampleType >::MaxNBuses (ERoute direction) const inline
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
Parameters
direction Return input or output bus count
Returns
The maximum bus count across all channel I/O configs
Definition at line 118 of file IPlugProcessor.h.
template<typename sampleType > int IPlugProcessor< sampleType >::MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
Parameters
direction Return input or output bus count
busIdx The index of the bus to look up
Returns
return The maximum number of channels on that bus
Definition at line 113 of file IPlugProcessor.cpp.
template<typename sampleType> int IPlugProcessor< sampleType >::NInChannels () const inline
Returns
Total number of input channel buffers
Definition at line 138 of file IPlugProcessor.h.
template<typename sampleType > int IPlugProcessor< sampleType >::NInChansConnected () const
Returns
The number of input channels connected. WARNING: this assumes consecutive channel connections
Definition at line 147 of file IPlugProcessor.cpp.
template<typename sampleType> int IPlugProcessor< sampleType >::NIOConfigs () const inline
Returns
The number of channel I/O configs derived from the channel io string
Definition at line 132 of file IPlugProcessor.h.
template<typename sampleType> int IPlugProcessor< sampleType >::NOutChannels () const inline
Returns
Total number of output channel buffers
Definition at line 141 of file IPlugProcessor.h.
template<typename sampleType > int IPlugProcessor< sampleType >::NOutChansConnected () const
Returns
The number of output channels connected. WARNING: this assumes consecutive channel connections
Definition at line 159 of file IPlugProcessor.cpp.
template<typename sampleType> int IPlugProcessor< sampleType >::NSidechainChannels () const inline
Returns
The number of channels and the side-chain input /todo this will change
Definition at line 167 of file IPlugProcessor.h.
template<typename sampleType> virtual void IPlugProcessor< sampleType >::OnActivate (bool active) inline virtual
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
This may not work reliably because different hosts have different interpretations of "activate". Unlike OnReset() which called when the transport is reset or the sample rate changes OnActivate() is a good place to handle change of I/O connections.
Parameters
active True if the host has activated the plug-in
Definition at line 58 of file IPlugProcessor.h.
template<typename sampleType> virtual void IPlugProcessor< sampleType >::OnIdle () inline virtual
Override this method to get an "idle"" call from the audio processing thread in VST2 plug-ins.
THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts Only active if USE_IDLE_CALLS preprocessor macro is defined
Definition at line 63 of file IPlugProcessor.h.
template<typename sampleType> virtual void IPlugProcessor< sampleType >::OnReset () inline virtual
Override this method in your plug-in class to do something prior to playback etc.
(e.g.clear buffers, update internal DSP with the latest sample rate)
Definition at line 52 of file IPlugProcessor.h.
template<typename sampleType > int IPlugProcessor< sampleType >::ParseChannelIOStr (const char * IOStr, WDL_PtrList< IOConfig > & channelIOList, int & totalNInChans, int & totalNOutChans, int & totalNInBuses, int & totalNOutBuses) static
A static method to parse the config.h channel I/O string.
Parameters
IOStr Space separated cstring list of I/O configurations for this plug-in in the format ninchans-noutchans. A hypen character (-) deliminates input-output. Supports multiple buses, which are indicated using a period (.) character. For instance plug-in that supports mono input and mono output with a mono side-chain input could have a channel io string of "1.1-1". A drum synthesiser with four stereo output busses could be configured with a io string of "0-2.2.2.2";
channelIOList A list of pointers to ChannelIO structs, where we will store here
totalNInChans The total number of input channels across all buses will be stored here
totalNOutChans The total number of output channels across all buses will be stored here
totalNInBuses The total number of input buses across all channel io configs will be stored here
totalNOutBuses The total number of output buses across all channel io configs will be stored here
Returns
The number of space separated channel io configs that have been detected in IOStr
Definition at line 228 of file IPlugProcessor.cpp.
template<typename sampleType> void IPlugProcessor< sampleType >::ProcessBlock (sampleType ** inputs, sampleType ** outputs, int nFrames) virtual
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
If the host hasn't connected all the pins, the unconnected channels will be full of zeros. THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Parameters
inputs Two-dimensional array containing the non-interleaved input buffers of audio samples for all channels
outputs Two-dimensional array for audio output (non-interleaved).
nFrames The block size for this block: number of samples per channel.
Definition at line 64 of file IPlugProcessor.cpp.
template<typename sampleType > void IPlugProcessor< sampleType >::ProcessMidiMsg (const IMidiMsg & msg) virtual
Override this method which is called prior to ProcessBlock(), to handle incoming MIDI messages.
You can use IMidiQueue in combination with this method in order to queue the message and process at the appropriate time in ProcessBlock() THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Parameters
msg The incoming midi message (includes a timestamp to indicate the offset in the forthcoming block of audio to be processed in ProcessBlock())
Definition at line 84 of file IPlugProcessor.cpp.
template<typename sampleType> virtual void IPlugProcessor< sampleType >::ProcessSysEx (ISysEx & msg) inline virtual
Override this method which is calledThis method is called prior to ProcessBlock(), to handle incoming MIDI System Exclusive (SysEx) messages.
THIS METHOD IS CALLED BY THE HIGH PRIORITY AUDIO THREAD - You should be careful not to do any unbounded, blocking operations such as file I/O which could cause audio dropouts
Definition at line 49 of file IPlugProcessor.h.
template<typename sampleType> virtual bool IPlugProcessor< sampleType >::SendMidiMsg (const IMidiMsg & msg) pure virtual
Send a single MIDI message.
Parameters
msg The IMidiMsg to send
Returns
/c true if successful
Implemented in IPlugAAX, IPlugAU, IPlugAPP, IPlugVST3, IPlugVST, and IPlugAUv3.
template<typename sampleType > bool IPlugProcessor< sampleType >::SendMidiMsgs (WDL_TypedBuf< IMidiMsg > & msgs)
Send a collection of MIDI messages.
Parameters
msg The IMidiMsg to send
Returns
/c true if successful
Definition at line 90 of file IPlugProcessor.cpp.
template<typename sampleType> virtual bool IPlugProcessor< sampleType >::SendSysEx (ISysEx & msg) inline virtual
Send a single MIDI System Exclusive (SysEx) message.
Parameters
msg The ISysEx to send
Returns
/c true if successful
Reimplemented in IPlugAPP, IPlugVST, and IPlugAUv3.
Definition at line 80 of file IPlugProcessor.h.
template<typename sampleType > void IPlugProcessor< sampleType >::SetInputLabel (int idx, const char * label)
This allows you to label input channels in supporting VST2 hosts.
For example a 4 channel plug-in that deals with FuMa bformat first order ambisonic material might label these channels "W", "X", "Y", "Z", rather than the default "input 1", "input 2", "input 3", "input 4"
Parameters
idx The index of the channel that you wish to label
label The label for the channel
Definition at line 198 of file IPlugProcessor.cpp.
template<typename sampleType > void IPlugProcessor< sampleType >::SetLatency (int latency) virtual
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
The method is virtual because it's overridden in API classes.
Parameters
samples Latency in samples
Reimplemented in IPlugAAX, IPlugAU, IPlugVST3, and IPlugVST.
Definition at line 216 of file IPlugProcessor.cpp.
Referenced by IPlugVST::SetLatency(), IPlugVST3::SetLatency(), IPlugAU::SetLatency(), and IPlugAAX::SetLatency().
template<typename sampleType > void IPlugProcessor< sampleType >::SetOutputLabel (int idx, const char * label)
This allows you to label output channels in supporting VST2 hosts.
For example a 4 channel plug-in that deals with FuMa bformat first order ambisonic material might label these channels "W", "X", "Y", "Z", rather than the default " output 1", " output 2", " output 3", " output 4"
Parameters
idx The index of the channel that you wish to label
label The label for the channel
Definition at line 207 of file IPlugProcessor.cpp.
template<typename sampleType> void IPlugProcessor< sampleType >::SetTailSize (int tailSize) inline
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
For VST3 set to 0xffffffff for infinite tail, or 0 for none (default) For VST2 setting to 1 means no tail
Parameters
tailSizeSamples the new tailsize in samples
Definition at line 199 of file IPlugProcessor.h.
Member Data Documentation
template<typename sampleType> NChanDelayLine<sampleType>* IPlugProcessor< sampleType >::mLatencyDelay = nullptr protected
Pointer to a multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
Definition at line 268 of file IPlugProcessor.h.
The documentation for this class was generated from the following files:
IPlugProcessor.h
IPlugProcessor.cpp