WDL-OL/IPlug: IGraphics Class Reference
IGraphics Class Reference abstract
The lowest level base class of an IGraphics context.
#include <IGraphics.h>
Public Member Functions
virtual void BeginFrame ()
virtual void EndFrame ()
virtual void ViewInitialized (void *layer)
virtual void SetDisplayScale (int scale)
Called by platform IGraphics class when UI created and when moving to a new screen with different DPI, implementations in draw class must call the base implementation.
virtual void DrawSVG (ISVG &svg, const IRECT &rect, const IBlend *pBlend=0)=0
Draw an SVG image to the graphics context.
virtual void DrawRotatedSVG (ISVG &svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawBitmap (IBitmap &bitmap, const IRECT &rect, int srcX, int srcY, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawRotatedBitmap (IBitmap &bitmap, int destCentreX, int destCentreY, double angle, int yOffsetZeroDeg=0, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawRotatedMask (IBitmap &base, IBitmap &mask, IBitmap &top, int x, int y, double angle, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void ForcePixel (const IColor &color, int x, int y)=0
/todo <#Description#>
virtual void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend=0)=0
<#Description#>
virtual void DrawRect (const IColor &color, const IRECT &rect, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawRoundRect (const IColor &color, const IRECT &rect, float cr=5.f, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend=0)=0
/todo
virtual void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void DrawDottedRect (const IColor &color, const IRECT &rect, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void FillRect (const IColor &color, const IRECT &rect, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void FillRoundRect (const IColor &color, const IRECT &rect, float cr=5.f, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void FillArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual void FillConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend=0)=0
/todo <#Description#>
virtual bool DrawText (const IText &text, const char *str, IRECT &destRect, bool measure=false)=0
/todo <#Description#>
virtual bool MeasureText (const IText &text, const char *str, IRECT &destRect)=0
/todo <#Description#>
virtual IColor GetPoint (int x, int y)=0
/todo <#Description#>
virtual void * GetData ()=0
/todo <#Description#>
virtual const char * GetDrawingAPIStr ()=0
/todo <#Description#>
virtual void ClipRegion (const IRECT &r)
/todo <#Description#>
virtual void ResetClipRegion ()
<#Description#>
virtual IBitmap LoadBitmap (const char *name, int nStates=1, bool framesAreHorizontal=false)
virtual IBitmap ScaleBitmap (const IBitmap &srcbitmap, const char *cacheName, int targetScale)
virtual void RetainBitmap (const IBitmap &bitmap, const char *cacheName)
virtual void ReleaseBitmap (const IBitmap &bitmap)
IBitmap GetScaledBitmap (IBitmap &src)
virtual void OnDisplayScale ()
<#Description#>
virtual void RenderDrawBitmap ()
Called by some drawing API classes to finally blit the draw bitmap onto the screen.
void DrawBitmap (IBitmap &bitmap, const IRECT &rect, int bmpState=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (IBitmap &bitmap, IRECT &rect, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws monospace bitmapped text.
void DrawVerticalLine (const IColor &color, const IRECT &rect, float x, const IBlend *pBlend=0)
/todo <#Description#>
void DrawHorizontalLine (const IColor &color, const IRECT &rect, float y, const IBlend *pBlend=0)
/todo <#Description#>
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0)
/todo <#Description#>
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0)
/todo <#Description#>
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0)
Helper function to draw a radial line, useful for pointers on dials.
void DrawGrid (const IColor &color, const IRECT &rect, int gridSizeH, int gridSizeV, const IBlend *pBlend)
/todo <#Description#>
virtual void HideMouseCursor ()
/todo <#Description#>
virtual void ShowMouseCursor ()
/todo <#Description#>
virtual void ForceEndUserEdit ()=0
/todo <#Description#>
virtual void Resize (int w, int h, float scale)
/todo <#Description#>
virtual void * OpenWindow (void *pParentWnd)=0
/todo <#Description#>
virtual void CloseWindow ()=0
/todo <#Description#>
virtual void * GetWindow ()=0
/todo <#Description#>
virtual bool GetTextFromClipboard (WDL_String &str)=0
/todo <#Description#>
virtual void UpdateTooltips ()=0
/todo <#Description#>
virtual int ShowMessageBox (const char *str, const char *caption, int type)=0
/todo <#Description#>
virtual IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, IRECT &textRect)=0
/todo <#Description#>
virtual void CreateTextEntry (IControl *pControl, const IText &text, const IRECT &textRect, const char *str="", IParam *pParam=0)=0
/todo <#Description#>
virtual void PromptForFile (WDL_String &filename, WDL_String &path, EFileAction action=kFileOpen, const char *extensions=0)=0
/todo <#Description#>
virtual bool PromptForColor (IColor &color, const char *str="")=0
/todo <#Description#>
virtual bool OpenURL (const char *url, const char *msgWindowTitle=0, const char *confirmMsg=0, const char *errMsgOnFailure=0)=0
/todo <#Description#>
virtual const char * GetGUIAPI ()
/todo <#Description#>
virtual bool WindowIsOpen ()
/todo <#Description#>
virtual void HostPath (WDL_String &path)=0
/todo <#Description#>
virtual void PluginPath (WDL_String &path)=0
/todo <#Description#>
virtual void DesktopPath (WDL_String &path)=0
/todo <#Description#>
virtual void UserHomePath (WDL_String &path)=0
/todo <#Description#>
virtual void AppSupportPath (WDL_String &path, bool isSystem=false)=0
/todo <#Description#>
virtual void SandboxSafeAppSupportPath (WDL_String &path)=0
/todo <#Description#>
virtual void VST3PresetsPath (WDL_String &path, bool isSystem=true)
/todo <#Description#>
virtual bool RevealPathInExplorerOrFinder (WDL_String &path, bool select=false)=0
/todo <#Description#>
virtual void SetPlatformInstance (void *pInstance)
virtual void * GetPlatformInstance ()
/todo <#Description#>
virtual void SetPlatformContext (void *pContext)
Used with IGraphicsLice (possibly others) in order to set the core graphics draw context on macOS and the GDI HDC draw context handle on Windows On macOS, this is called by the platform IGraphics class IGraphicsMac, on Windows it is called by the drawing class e.g.
void * GetPlatformContext ()
/todo <#Description#>
virtual bool OSFindResource (const char *name, const char *type, WDL_String &result)=0
Try to ascertain the full path of a resource.
IGraphics (IPlugBaseGraphics &plug, int w, int h, int fps=0)
bool IsDirty (IRECT &rect)
/todo <#Description#>
virtual void Draw (const IRECT &rect)
/todo <#Description#>
virtual ISVG LoadSVG (const char *name)
/todo <#Description#>
void PromptUserInput (IControl *pControl, IParam *pParam, IRECT &textRect)
/todo <#Description#>
void SetFromStringAfterPrompt (IControl *pControl, IParam *pParam, const char *txt)
/todo <#Description#>
IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, float x, float y)
/todo <#Description#>
void SetStrictDrawing (bool strict)
/todo <#Description#>
int Width () const
/todo <#Description#>
int Height () const
/todo <#Description#>
int WindowWidth () const
/todo <#Description#>
int WindowHeight () const
/todo <#Description#>
int FPS () const
/todo <#Description#>
float GetScale () const
/todo <#Description#>
float GetDisplayScale () const
/todo <#Description#>
IPlugBaseGraphics & GetPlug ()
/todo <#Description#>
void AttachBackground (const char *name)
void AttachPanelBackground (const IColor &color)
void AttachKeyCatcher (IControl &control)
int AttachControl (IControl *pControl)
/todo <#Description#>
IControl * GetControl (int idx)
/todo <#Description#>
int NControls () const
/todo <#Description#>
void HideControl (int paramIdx, bool hide)
/todo <#Description#>
void GrayOutControl (int paramIdx, bool gray)
/todo <#Description#>
void ClampControl (int paramIdx, double lo, double hi, bool normalized)
/todo <#Description#>
void SetAllControlsDirty ()
/todo <#Description#>
void SetControlFromPlug (int controlIdx, double normalizedValue)
/todo <#Description#>
void SetParameterFromPlug (int paramIdx, double value, bool normalized)
/todo <#Description#>
void SetParameterFromGUI (int paramIdx, double normalizedValue)
/todo <#Description#>
void OnMouseDown (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseUp (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
/todo <#Description#>
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
/todo <#Description#>
bool OnKeyDown (float x, float y, int key)
/todo <#Description#>
bool OnMouseOver (float x, float y, const IMouseMod &mod)
/todo <#Description#>
void OnMouseOut ()
/todo <#Description#>
void OnDrop (const char *str, float x, float y)
/todo <#Description#>
void OnGUIIdle ()
/todo <#Description#>
int GetParamIdxForPTAutomation (float x, float y)
[AAX only]
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily]
void HandleMouseOver (bool canHandle)
/todo <#Description#>
void ReleaseMouseCapture ()
/todo <#Description#>
void EnableTooltips (bool enable)
/todo <#Description#>
void AssignParamNameToolTips ()
/todo <#Description#>
void ShowControlBounds (bool enable)
/todo <#Description#>
void ShowAreaDrawn (bool enable)
/todo <#Description#>
void EnableLiveEdit (bool enable, const char *file=0, int gridsize=10)
/todo <#Description#>
IRECT GetDrawRect () const
/todo Get the area marked for drawing
IRECT GetBounds () const
Get an IRECT that represents the entire UI bounds.
bool CanHandleMouseOver () const
/todo <#Description#>
int GetMouseOver () const
/todo <#Description#>
bool TooltipsEnabled () const
/todo <#Description#>
virtual void LoadFont (const char *name)
/todo <#Description#>
Protected Member Functions
virtual APIBitmap * LoadAPIBitmap (const WDL_String &resourcePath, int scale)=0
virtual APIBitmap * ScaleAPIBitmap (const APIBitmap *pBitmap, int scale)=0
void SearchNextScale (int &sourceScale, int targetScale)
bool SearchImageResource (const char *name, const char *type, WDL_String &result, int targetScale, int &sourceScale)
APIBitmap * SearchBitmapInCache (const char *name, int targetScale, int &sourceScale)
Protected Attributes
IPlugBaseGraphics & mPlug
WDL_PtrList< IControl > mControls
IRECT mDrawRECT
void * mPlatformContext = nullptr
bool mCursorHidden = false
FT_Library mFTLibrary = nullptr
FT_Face mFTFace = nullptr
Friends
class IGraphicsLiveEdit
Detailed Description
The lowest level base class of an IGraphics context.
Definition at line 41 of file IGraphics.h.
Member Function Documentation
virtual void IGraphics::AppSupportPath (WDL_String & path, bool isSystem = false) pure virtual
/todo <#Description#>
Parameters
path <#path description#>
isSystem <#isSystem description#>
Implemented in IGraphicsMac, and IGraphicsWin.
int IGraphics::AttachControl (IControl * pControl)
/todo <#Description#>
Parameters
control <#control description#>
Returns
<#return value description#>
Definition at line 118 of file IGraphics.cpp.
bool IGraphics::CanHandleMouseOver () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 1098 of file IGraphics.h.
void IGraphics::ClampControl (int paramIdx, double lo, double hi, bool normalized)
/todo <#Description#>
Parameters
paramIdx <#paramIdx description#>
lo <#lo description#>
hi <#hi description#>
normalized <#normalized description#>
Definition at line 159 of file IGraphics.cpp.
References IControl::ParamIdx().
virtual void IGraphics::ClipRegion (const IRECT & r) inline virtual
/todo <#Description#>
Parameters
r <#r description#>
Returns
<#return value description#>
Reimplemented in IGraphicsCairo.
Definition at line 344 of file IGraphics.h.
Referenced by Draw().
virtual IPopupMenu* IGraphics::CreateIPopupMenu (IPopupMenu & menu, IRECT & textRect) pure virtual
/todo <#Description#>
Parameters
menu <#menu description#>
textRect <#textRect description#>
Returns
<#return value description#>
Implemented in IGraphicsWin, and IGraphicsMac.
Referenced by PopupHostContextMenuForParam(), and PromptUserInput().
IPopupMenu* IGraphics::CreateIPopupMenu (IPopupMenu & menu, float x, float y) inline
/todo <#Description#>
Parameters
menu <#menu description#>
x <#x description#>
y <#y description#>
Returns
<#return value description#>
Definition at line 750 of file IGraphics.h.
References CreateIPopupMenu().
Referenced by CreateIPopupMenu().
virtual void IGraphics::CreateTextEntry (IControl * pControl, const IText & text, const IRECT & textRect, const char * str = "", IParam * pParam = 0) pure virtual
/todo <#Description#>
Parameters
pControl <#pControl description#>
text <#text description#>
textRect <#textRect description#>
"" <#"" description#>
pParam <#pParam description#>
Implemented in IGraphicsWin, and IGraphicsMac.
Referenced by PromptUserInput().
virtual void IGraphics::DesktopPath (WDL_String & path) pure virtual
/todo <#Description#>
Parameters
path <#path description#>
Implemented in IGraphicsMac, and IGraphicsWin.
void IGraphics::Draw (const IRECT & rect) virtual
/todo <#Description#>
Parameters
rect The rectangular area to draw/fill the shape in
Reimplemented in IGraphicsAGG.
Definition at line 472 of file IGraphics.cpp.
References ClipRegion(), DrawRect(), FillRect(), IControl::IsHidden(), RenderDrawBitmap(), and ResetClipRegion().
Referenced by IGraphicsAGG::Draw().
virtual void IGraphics::DrawArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend = 0) pure virtual
/todo
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
aMin the start angle of the arc at in degrees clockwise where 0 is up /see IGraphicsDrawing documentation
aMax the end angle of the arc at in degrees clockwise where 0 is up /see IGraphicsDrawing documentation
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawBitmap (IBitmap & bitmap, const IRECT & rect, int srcX, int srcY, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
bitmap The bitmap image to draw to the graphics context
rect The rectangular area to draw the image in
srcX <#srcX description#>
srcY <#srcY description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
Referenced by DrawBitmap(), and DrawBitmapedText().
void IGraphics::DrawBitmap (IBitmap & bitmap, const IRECT & rect, int bmpState = 1, const IBlend * pBlend = 0)
Draws a bitmap into the graphics context.
Parameters
bitmap - the bitmap to draw
rect - where to draw the bitmap
bmpState - the frame of the bitmap to draw
pBlend - blend operation
Definition at line 292 of file IGraphics.cpp.
References DrawBitmap(), IBitmap::GetFramesAreHorizontal(), IBitmap::H(), IBitmap::N(), and IBitmap::W().
void IGraphics::DrawBitmapedText (IBitmap & bitmap, IRECT & rect, IText & text, IBlend * pBlend, const char * str, bool vCenter = true, bool multiline = false, int charWidth = 6, int charHeight = 12, int charOffset = 0)
Draws monospace bitmapped text.
Useful for identical looking text on multiple platforms.
Parameters
bitmap the bitmap containing glyphs to draw
rect where to draw the bitmap
text text properties (note - many of these are irrelevant for bitmapped text)
pBlend blend operation
str the string to draw
vCenter centre the text vertically
multiline should the text spill onto multiple lines
charWidth how wide is a character in the bitmap
charHeight how high is a character in the bitmap
charOffset what is the offset between characters drawn
Definition at line 311 of file IGraphics.cpp.
References DrawBitmap().
virtual void IGraphics::DrawCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawConvexPolygon (const IColor & color, float * x, float * y, int npoints, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
npoints <#npoints description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawDottedRect (const IColor & color, const IRECT & rect, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
void IGraphics::DrawGrid (const IColor & color, const IRECT & rect, int gridSizeH, int gridSizeV, const IBlend * pBlend)
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
gridSizeH <#gridSizeH description#>
gridSizeV <#gridSizeV description#>
pBlend Optional blend method, see IBlend documentation
Definition at line 412 of file IGraphics.cpp.
References DrawHorizontalLine(), and DrawVerticalLine().
void IGraphics::DrawHorizontalLine (const IColor & color, const IRECT & rect, float y, const IBlend * pBlend = 0)
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
y <#y description#>
pBlend Optional blend method, see IBlend documentation
Definition at line 383 of file IGraphics.cpp.
References BOUNDED.
Referenced by DrawGrid().
void IGraphics::DrawHorizontalLine (const IColor & color, float yi, float xLo, float xHi, const IBlend * pBlend = 0)
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
yi <#yi description#>
xLo <#xLo description#>
xHi <#xHi description#>
pBlend Optional blend method, see IBlend documentation
Definition at line 395 of file IGraphics.cpp.
References DrawLine().
virtual void IGraphics::DrawLine (const IColor & color, float x1, float y1, float x2, float y2, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x1 <#x1 description#>
y1 <#y1 description#>
x2 <#x2 description#>
y2 <#y2 description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
Referenced by DrawHorizontalLine(), DrawRadialLine(), and DrawVerticalLine().
virtual void IGraphics::DrawPoint (const IColor & color, float x, float y, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
void IGraphics::DrawRadialLine (const IColor & color, float cx, float cy, float angle, float rMin, float rMax, const IBlend * pBlend = 0)
Helper function to draw a radial line, useful for pointers on dials.
Parameters
color the colour of the line
cx centre point x coordinate
cy centre point y coordinate
angle the angle to draw at in degrees clockwise where 0 is up /see IGraphicsDrawing documentation
rMin minima of the radial line (distance from cx,cy)
rMax maxima of the radial line (distance from cx,cy)
pBlend blend operation
Definition at line 400 of file IGraphics.cpp.
References DrawLine().
virtual void IGraphics::DrawRect (const IColor & color, const IRECT & rect, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
Referenced by Draw().
virtual void IGraphics::DrawRotatedBitmap (IBitmap & bitmap, int destCentreX, int destCentreY, double angle, int yOffsetZeroDeg = 0, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
bitmap The bitmap image to draw to the graphics context
destCentreX The X coordinate of the centre point at which to rotate the image around. /todo check this
destCentreY The Y coordinate of the centre point at which to rotate the image around. /todo check this
angle The angle of rotation in degrees
yOffsetZeroDeg /todo
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawRotatedMask (IBitmap & base, IBitmap & mask, IBitmap & top, int x, int y, double angle, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
angle the angle to rotate the bitmap mask at in degrees clockwise /see IGraphicsDrawing documentation
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawRotatedSVG (ISVG & svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
svg The svg image to draw to the graphics context
destCentreX The X coordinate of the centre point at which to rotate the image around. /todo check this
destCentreY The Y coordinate of the centre point at which to rotate the image around. /todo check this
width /todo
height /todo
angle angle the angle to rotate the bitmap mask at in degrees clockwise /see IGraphicsDrawing documentation
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawRoundRect (const IColor & color, const IRECT & rect, float cr = 5.f, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
.f <#.f description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawSVG (ISVG & svg, const IRECT & rect, const IBlend * pBlend = 0) pure virtual
Draw an SVG image to the graphics context.
Parameters
svg The image to draw
rect The rectangular area to draw the image in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual bool IGraphics::DrawText (const IText & text, const char * str, IRECT & destRect, bool measure = false) pure virtual
/todo <#Description#>
Parameters
text <#text description#>
str <#str description#>
destRect <#destRect description#>
measure <#measure description#>
Returns
<#return value description#>
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::DrawTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend = 0) pure virtual
<#Description#>
Parameters
color <#color description#>
x1 <#x1 description#>
y1 <#y1 description#>
x2 <#x2 description#>
y2 <#y2 description#>
x3 <#x3 description#>
y3 <#y3 description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
void IGraphics::DrawVerticalLine (const IColor & color, const IRECT & rect, float x, const IBlend * pBlend = 0)
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
x <#x description#>
pBlend Optional blend method, see IBlend documentation
Definition at line 376 of file IGraphics.cpp.
References BOUNDED.
Referenced by DrawGrid().
void IGraphics::DrawVerticalLine (const IColor & color, float xi, float yLo, float yHi, const IBlend * pBlend = 0)
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
xi <#xi description#>
yLo <#yLo description#>
yHi <#yHi description#>
pBlend Optional blend method, see IBlend documentation
Definition at line 390 of file IGraphics.cpp.
References DrawLine().
void IGraphics::EnableLiveEdit (bool enable, const char * file = 0, int gridsize = 10)
/todo <#Description#>
Parameters
enable <#enable description#>
file <#file description#>
gridsize <#gridsize description#>
Definition at line 959 of file IGraphics.cpp.
References GetPlug().
void IGraphics::EnableTooltips (bool enable)
/todo <#Description#>
Parameters
enable <#enable description#>
Definition at line 952 of file IGraphics.cpp.
Referenced by IGraphicsWin::OpenWindow().
virtual void IGraphics::FillArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
aMin <#aMin description#>
aMax <#aMax description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::FillCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
cx <#cx description#>
cy <#cy description#>
r <#r description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::FillConvexPolygon (const IColor & color, float * x, float * y, int npoints, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
npoints <#npoints description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::FillRect (const IColor & color, const IRECT & rect, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
Referenced by Draw().
virtual void IGraphics::FillRoundRect (const IColor & color, const IRECT & rect, float cr = 5.f, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
rect The rectangular area to draw/fill the shape in
.f <#.f description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::FillTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend = 0) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x1 <#x1 description#>
y1 <#y1 description#>
x2 <#x2 description#>
y2 <#y2 description#>
x3 <#x3 description#>
y3 <#y3 description#>
pBlend Optional blend method, see IBlend documentation
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
virtual void IGraphics::ForcePixel (const IColor & color, int x, int y) pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
x <#x description#>
y <#y description#>
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
int IGraphics::FPS () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 792 of file IGraphics.h.
Referenced by IGraphicsWin::OpenWindow().
IRECT IGraphics::GetBounds () const inline
Get an IRECT that represents the entire UI bounds.
Returns
An IRECT that corresponds to the entire UI area, with, L = 0, T = 0, R = Width() and B = Height()
Definition at line 1091 of file IGraphics.h.
References Height(), and Width().
IControl* IGraphics::GetControl (int idx) inline
/todo <#Description#>
Parameters
idx <#idx description#>
Returns
<#return value description#>
Definition at line 833 of file IGraphics.h.
Referenced by OnDrop(), and PopupHostContextMenuForParam().
float IGraphics::GetDisplayScale () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 806 of file IGraphics.h.
Referenced by IGraphicsLice::DrawArc(), IGraphicsAGG::DrawArc(), IGraphicsLice::DrawBitmap(), IGraphicsAGG::DrawBitmap(), IGraphicsLice::DrawCircle(), IGraphicsAGG::DrawCircle(), IGraphicsLice::DrawConvexPolygon(), IGraphicsAGG::DrawConvexPolygon(), IGraphicsLice::DrawDottedRect(), IGraphicsLice::DrawLine(), IGraphicsAGG::DrawLine(), IGraphicsLice::DrawPoint(), IGraphicsAGG::DrawPoint(), IGraphicsLice::DrawRect(), IGraphicsLice::DrawRotatedBitmap(), IGraphicsAGG::DrawRotatedBitmap(), IGraphicsAGG::DrawRotatedMask(), IGraphicsLice::DrawRoundRect(), IGraphicsAGG::DrawRoundRect(), IGraphicsLice::DrawText(), IGraphicsLice::DrawTriangle(), IGraphicsAGG::FillArc(), IGraphicsLice::FillCircle(), IGraphicsAGG::FillCircle(), IGraphicsLice::FillConvexPolygon(), IGraphicsAGG::FillConvexPolygon(), IGraphicsLice::FillRect(), IGraphicsLice::FillRoundRect(), IGraphicsAGG::FillRoundRect(), IGraphicsLice::FillTriangle(), IGraphicsLice::ForcePixel(), IGraphicsAGG::ForcePixel(), IGraphicsLice::GetPoint(), and IGraphicsAGG::RenderDrawBitmap().
virtual const char* IGraphics::GetDrawingAPIStr () pure virtual
/todo <#Description#>
Returns
<#return value description#>
Implemented in IGraphicsAGG, IGraphicsLice, IGraphicsNanoVG, and IGraphicsCairo.
IRECT IGraphics::GetDrawRect () const inline
/todo Get the area marked for drawing
Returns
An IRECT that corresponds to the area currently marked for drawing
Definition at line 1083 of file IGraphics.h.
Referenced by IGraphicsLice::DrawRotatedSVG().
virtual const char* IGraphics::GetGUIAPI () inline virtual
/todo <#Description#>
Returns
<#return value description#>
Reimplemented in IGraphicsWin, and IGraphicsMac.
Definition at line 587 of file IGraphics.h.
int IGraphics::GetLastClickedParamForPTAutomation ()
[AAX only]
Returns
<#return value description#>
Definition at line 848 of file IGraphics.cpp.
int IGraphics::GetMouseOver () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 1105 of file IGraphics.h.
int IGraphics::GetParamIdxForPTAutomation (float x, float y)
[AAX only]
Parameters
x <#x description#>
y <#y description#>
Returns
<#return value description#>
Definition at line 836 of file IGraphics.cpp.
void* IGraphics::GetPlatformContext () inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 685 of file IGraphics.h.
Referenced by IGraphicsLice::RenderDrawBitmap(), and IGraphicsAGG::RenderDrawBitmap().
IPlugBaseGraphics& IGraphics::GetPlug () inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 813 of file IGraphics.h.
Referenced by EnableLiveEdit().
virtual IColor IGraphics::GetPoint (int x, int y) pure virtual
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
Returns
<#return value description#>
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, and IGraphicsCairo.
float IGraphics::GetScale () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 799 of file IGraphics.h.
Referenced by IGraphicsCairo::RenderDrawBitmap(), IGraphicsLice::RenderDrawBitmap(), IGraphicsMac::Resize(), IGraphicsWin::Resize(), and IGraphicsCairo::SetPlatformContext().
virtual bool IGraphics::GetTextFromClipboard (WDL_String & str) pure virtual
/todo <#Description#>
Parameters
str <#str description#>
Returns
<#return value description#>
Implemented in IGraphicsWin, and IGraphicsMac.
void IGraphics::GrayOutControl (int paramIdx, bool gray)
/todo <#Description#>
Parameters
paramIdx <#paramIdx description#>
gray <#gray description#>
Definition at line 144 of file IGraphics.cpp.
References IControl::GrayOut(), and IControl::ParamIdx().
void IGraphics::HandleMouseOver (bool canHandle) inline
/todo <#Description#>
Parameters
canHandle <#canHandle description#>
Definition at line 1035 of file IGraphics.h.
int IGraphics::Height () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 771 of file IGraphics.h.
Referenced by GetBounds(), IGraphicsCairo::RenderDrawBitmap(), IGraphicsLice::RenderDrawBitmap(), IGraphicsMac::Resize(), IGraphicsWin::Resize(), IGraphicsLice::SetDisplayScale(), IGraphicsAGG::SetDisplayScale(), and IGraphicsCairo::SetPlatformContext().
void IGraphics::HideControl (int paramIdx, bool hide)
/todo <#Description#>
Parameters
paramIdx <#paramIdx description#>
hide <#hide description#>
Definition at line 129 of file IGraphics.cpp.
References IControl::Hide(), and IControl::ParamIdx().
virtual void IGraphics::HostPath (WDL_String & path) pure virtual
/todo <#Description#>
Parameters
path <#path description#>
Implemented in IGraphicsMac, and IGraphicsWin.
bool IGraphics::IsDirty (IRECT & rect)
/todo <#Description#>
Parameters
rect The rectangular area to draw/fill the shape in
Returns
<#return value description#>
Definition at line 432 of file IGraphics.cpp.
References OnGUIIdle().
void IGraphics::LoadFont (const char * name) virtual
/todo <#Description#>
Parameters
name <#name description#>
Definition at line 992 of file IGraphics.cpp.
Referenced by IGraphicsCairo::DrawText().
ISVG IGraphics::LoadSVG (const char * name) virtual
/todo <#Description#>
Parameters
name <#name description#>
Returns
<#return value description#>
Definition at line 972 of file IGraphics.cpp.
References OSFindResource().
virtual bool IGraphics::MeasureText (const IText & text, const char * str, IRECT & destRect) pure virtual
/todo <#Description#>
Parameters
text <#text description#>
str <#str description#>
destRect <#destRect description#>
Returns
<#return value description#>
Implemented in IGraphicsAGG, IGraphicsNanoVG, IGraphicsLice, IGraphicsMac, and IGraphicsCairo.
int IGraphics::NControls () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 840 of file IGraphics.h.
void IGraphics::OnDrop (const char * str, float x, float y)
/todo <#Description#>
Parameters
str <#str description#>
x <#x description#>
y <#y description#> /todo <#Description#>
str <#str description#>
x <#x description#>
y <#y description#>
Definition at line 944 of file IGraphics.cpp.
References GetControl(), and IControl::OnDrop().
bool IGraphics::OnKeyDown (float x, float y, int key)
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
key <#key description#>
Returns
<#return value description#>
Definition at line 784 of file IGraphics.cpp.
bool IGraphics::OnMouseDblClick (float x, float y, const IMouseMod & mod)
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
mod <#mod description#>
Returns
<#return value description#>
Definition at line 745 of file IGraphics.cpp.
References ReleaseMouseCapture().
void IGraphics::OnMouseDown (float x, float y, const IMouseMod & mod)
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
mod <#mod description#>
Definition at line 596 of file IGraphics.cpp.
References IControl::ParamIdx(), PopupHostContextMenuForParam(), and ReleaseMouseCapture().
void IGraphics::OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod & mod)
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
dX <#dX description#>
dY <#dY description#>
mod <#mod description#>
Definition at line 727 of file IGraphics.cpp.
bool IGraphics::OnMouseOver (float x, float y, const IMouseMod & mod)
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
mod <#mod description#>
Returns
<#return value description#>
Definition at line 683 of file IGraphics.cpp.
void IGraphics::OnMouseUp (float x, float y, const IMouseMod & mod)
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
mod <#mod description#>
Definition at line 656 of file IGraphics.cpp.
References IControl::ParamIdx(), and ReleaseMouseCapture().
void IGraphics::OnMouseWheel (float x, float y, const IMouseMod & mod, float d)
/todo <#Description#>
Parameters
x <#x description#>
y <#y description#>
mod <#mod description#>
d <#d description#>
Definition at line 770 of file IGraphics.cpp.
virtual bool IGraphics::OpenURL (const char * url, const char * msgWindowTitle = 0, const char * confirmMsg = 0, const char * errMsgOnFailure = 0) pure virtual
/todo <#Description#>
Parameters
url <#url description#>
msgWindowTitle <#msgWindowTitle description#>
confirmMsg <#confirmMsg description#>
errMsgOnFailure <#errMsgOnFailure description#>
Returns
<#return value description#>
Implemented in IGraphicsWin, and IGraphicsMac.
virtual void* IGraphics::OpenWindow (void * pParentWnd) pure virtual
/todo <#Description#>
Parameters
pParentWnd <#pParentWnd description#>
Implemented in IGraphicsWin, and IGraphicsMac.
virtual bool IGraphics::OSFindResource (const char * name, const char * type, WDL_String & result) pure virtual
Try to ascertain the full path of a resource.
Parameters
name <#name description#>
type <#type description#>
result <#result description#>
Returns
<#return value description#>
Implemented in IGraphicsWin, and IGraphicsMac.
Referenced by LoadSVG().
virtual void IGraphics::PluginPath (WDL_String & path) pure virtual
/todo <#Description#>
Parameters
path <#path description#>
Implemented in IGraphicsMac, and IGraphicsWin.
void IGraphics::PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily]
Parameters
controlIdx <#controlIdx description#>
paramIdx <#paramIdx description#>
x <#x description#>
y <#y description#>
Definition at line 870 of file IGraphics.cpp.
References IControl::CreateContextMenu(), CreateIPopupMenu(), GetControl(), and IControl::OnContextSelection().
Referenced by OnMouseDown().
virtual bool IGraphics::PromptForColor (IColor & color, const char * str = "") pure virtual
/todo <#Description#>
Parameters
color The colour to draw/fill the shape with>
"" <#"" description#>
Returns
<#return value description#>
Implemented in IGraphicsMac, and IGraphicsWin.
virtual void IGraphics::PromptForFile (WDL_String & filename, WDL_String & path, EFileAction action = kFileOpen, const char * extensions = 0) pure virtual
/todo <#Description#>
Parameters
filename <#filename description#>
path <#path description#>
action <#action description#>
extensions <#extensions description#>
Implemented in IGraphicsMac, and IGraphicsWin.
void IGraphics::PromptUserInput (IControl * pControl, IParam * pParam, IRECT & textRect)
/todo <#Description#>
Parameters
pControl <#pControl description#>
pParam <#pParam description#>
textRect <#textRect description#>
Definition at line 254 of file IGraphics.cpp.
References CreateIPopupMenu(), and CreateTextEntry().
virtual void IGraphics::RenderDrawBitmap () inline virtual
Called by some drawing API classes to finally blit the draw bitmap onto the screen.
<#Description#>
Reimplemented in IGraphicsAGG, IGraphicsLice, and IGraphicsCairo.
Definition at line 372 of file IGraphics.h.
Referenced by Draw().
virtual void IGraphics::ResetClipRegion () inline virtual
<#Description#>
Returns
<#return value description#>
Reimplemented in IGraphicsCairo.
Definition at line 351 of file IGraphics.h.
Referenced by Draw().
void IGraphics::Resize (int w, int h, float scale) virtual
/todo <#Description#>
Parameters
w <#w description#>
h <#h description#>
scale <#scale description#>
Reimplemented in IGraphicsWin, and IGraphicsMac.
Definition at line 67 of file IGraphics.cpp.
References OnDisplayScale(), ReleaseMouseCapture(), and SetParameterFromPlug().
Referenced by IGraphicsMac::Resize(), and IGraphicsWin::Resize().
virtual bool IGraphics::RevealPathInExplorerOrFinder (WDL_String & path, bool select = false) pure virtual
/todo <#Description#>
Parameters
path <#path description#>
select <#select description#>
Returns
<#return value description#>
Implemented in IGraphicsMac, and IGraphicsWin.
virtual void IGraphics::SandboxSafeAppSupportPath (WDL_String & path) pure virtual
/todo <#Description#>
Parameters
path <#path description#>
Implemented in IGraphicsMac, and IGraphicsWin.
void IGraphics::SetControlFromPlug (int controlIdx, double normalizedValue)
/todo <#Description#>
Parameters
controlIdx <#controlIdx description#>
normalizedValue <#normalizedValue description#>
Definition at line 208 of file IGraphics.cpp.
virtual void IGraphics::SetDisplayScale (int scale) inline virtual
Called by platform IGraphics class when UI created and when moving to a new screen with different DPI, implementations in draw class must call the base implementation.
Parameters
scale An integer specifying the scale of the display, where 2 = mac retina /todo better explanation of scale
Reimplemented in IGraphicsAGG, and IGraphicsLice.
Definition at line 60 of file IGraphics.h.
References OnDisplayScale().
Referenced by IGraphicsLice::SetDisplayScale(), and IGraphicsAGG::SetDisplayScale().
void IGraphics::SetFromStringAfterPrompt (IControl * pControl, IParam * pParam, const char * txt)
/todo <#Description#>
Parameters
pControl <#pControl description#>
pParam <#pParam description#>
txt <#txt description#>
Definition at line 97 of file IGraphics.cpp.
void IGraphics::SetParameterFromGUI (int paramIdx, double normalizedValue)
/todo <#Description#>
Parameters
paramIdx <#paramIdx description#>
normalizedValue <#normalizedValue description#>
Definition at line 241 of file IGraphics.cpp.
References IControl::ParamIdx().
void IGraphics::SetParameterFromPlug (int paramIdx, double value, bool normalized)
/todo <#Description#>
Parameters
paramIdx <#paramIdx description#>
value <#value description#>
normalized <#normalized description#>
Definition at line 180 of file IGraphics.cpp.
References IControl::AuxParamIdx(), IControl::ParamIdx(), and IControl::SetAuxParamValueFromPlug().
Referenced by Resize().
virtual void IGraphics::SetPlatformContext (void * pContext) inline virtual
Used with IGraphicsLice (possibly others) in order to set the core graphics draw context on macOS and the GDI HDC draw context handle on Windows On macOS, this is called by the platform IGraphics class IGraphicsMac, on Windows it is called by the drawing class e.g.
IGraphicsLice.
Parameters
pContext <#pContext description#>
Reimplemented in IGraphicsCairo.
Definition at line 678 of file IGraphics.h.
Referenced by IGraphicsWin::CloseWindow(), IGraphicsWin::OpenWindow(), and IGraphicsCairo::SetPlatformContext().
void IGraphics::SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
Parameters
paramIdx <#paramIdx description#>
isHighlighted <#isHighlighted description#>
color The colour to draw/fill the shape with>
Definition at line 855 of file IGraphics.cpp.
References IControl::ParamIdx().
void IGraphics::SetStrictDrawing (bool strict)
/todo <#Description#>
Parameters
strict <#strict description#>
Definition at line 590 of file IGraphics.cpp.
References SetAllControlsDirty().
void IGraphics::ShowAreaDrawn (bool enable) inline
/todo <#Description#>
Parameters
enable <#enable description#>
Definition at line 1067 of file IGraphics.h.
void IGraphics::ShowControlBounds (bool enable) inline
/todo <#Description#>
Parameters
enable <#enable description#>
Definition at line 1059 of file IGraphics.h.
virtual int IGraphics::ShowMessageBox (const char * str, const char * caption, int type) pure virtual
/todo <#Description#>
Parameters
str <#str description#>
caption <#caption description#>
type <#type description#>
Returns
<#return value description#>
Implemented in IGraphicsMac, and IGraphicsWin.
bool IGraphics::TooltipsEnabled () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 1112 of file IGraphics.h.
Referenced by IGraphicsWin::OpenWindow(), and IGraphicsMac::UpdateTooltips().
virtual void IGraphics::UserHomePath (WDL_String & path) pure virtual
/todo <#Description#>
Parameters
path <#path description#>
Implemented in IGraphicsMac, and IGraphicsWin.
virtual void IGraphics::VST3PresetsPath (WDL_String & path, bool isSystem = true) inline virtual
/todo <#Description#>
Parameters
path <#path description#>
isSystem <#isSystem description#>
Reimplemented in IGraphicsMac, and IGraphicsWin.
Definition at line 647 of file IGraphics.h.
int IGraphics::Width () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 764 of file IGraphics.h.
Referenced by GetBounds(), IGraphicsCairo::RenderDrawBitmap(), IGraphicsLice::RenderDrawBitmap(), IGraphicsMac::Resize(), IGraphicsWin::Resize(), IGraphicsLice::SetDisplayScale(), IGraphicsAGG::SetDisplayScale(), and IGraphicsCairo::SetPlatformContext().
int IGraphics::WindowHeight () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 785 of file IGraphics.h.
Referenced by IGraphicsWin::CreateIPopupMenu(), IGraphicsWin::OpenWindow(), IGraphicsCairo::RenderDrawBitmap(), IGraphicsLice::RenderDrawBitmap(), and IGraphicsWin::Resize().
virtual bool IGraphics::WindowIsOpen () inline virtual
/todo <#Description#>
Returns
<#return value description#>
Reimplemented in IGraphicsWin, and IGraphicsMac.
Definition at line 595 of file IGraphics.h.
References GetWindow().
int IGraphics::WindowWidth () const inline
/todo <#Description#>
Returns
<#return value description#>
Definition at line 778 of file IGraphics.h.
Referenced by IGraphicsWin::CreateIPopupMenu(), IGraphicsWin::OpenWindow(), IGraphicsCairo::RenderDrawBitmap(), IGraphicsLice::RenderDrawBitmap(), and IGraphicsWin::Resize().
The documentation for this class was generated from the following files:
IGraphics.h
IGraphics.cpp