WDL-OL/IPlug: IBitmap Class Reference
IBitmap Class Reference
IGraphics::Structs
Used to manage bitmap data, independant of draw class/platform.
#include <IGraphicsStructs.h>
Public Member Functions
IBitmap (APIBitmap *pAPIBitmap, int n, bool framesAreHorizontal, const char *name="")
Creates a new IBitmap object.
int W () const
int H () const
int FW () const
int FH () const
int N () const
APIBitmap * GetAPIBitmap () const
void * GetRawBitmap () const
bool GetFramesAreHorizontal () const
const WDL_String & GetResourceName () const
Detailed Description
Used to manage bitmap data, independant of draw class/platform.
An IBitmap's width and height are always in relation to a 1:1 (low dpi) screen. Any scaling happens at the drawing stage.
Definition at line 64 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IBitmap::IBitmap (APIBitmap * pAPIBitmap, int n, bool framesAreHorizontal, const char * name = "") inline
Creates a new IBitmap object.
Parameters
pData Pointer to the raw bitmap data
w Bitmap width (in pixels)
h Bitmap height (in pixels)
n Number of frames (for multibitmaps)
framesAreHorizontal True if the frames are positioned horizontally
sourceScale Scaling of the original bitmap (typically 1, 2 would be for a @2x hi dpi bitmap)
Todo:
Subject to change
Parameters
name Resource name for the bitmap
Definition at line 79 of file IGraphicsStructs.h.
Member Function Documentation
int IBitmap::FH () const inline
Returns
Height of a single frame
Definition at line 109 of file IGraphicsStructs.h.
int IBitmap::FW () const inline
Returns
Width of a single frame
Definition at line 105 of file IGraphicsStructs.h.
APIBitmap* IBitmap::GetAPIBitmap () const inline
Returns
a pointer to the referencied APIBitmap
Definition at line 117 of file IGraphicsStructs.h.
Referenced by IGraphicsNanoVG::DrawBitmap(), and IGraphicsNanoVG::DrawRotatedBitmap().
bool IBitmap::GetFramesAreHorizontal () const inline
Returns
whether or not frames are stored horiztonally
Definition at line 125 of file IGraphicsStructs.h.
Referenced by IGraphics::DrawBitmap().
void* IBitmap::GetRawBitmap () const inline
Returns
the raw underlying bitmap
Definition at line 121 of file IGraphicsStructs.h.
Referenced by IGraphicsCairo::DrawBitmap(), IGraphicsLice::DrawBitmap(), IGraphicsAGG::DrawBitmap(), IGraphicsLice::DrawRotatedBitmap(), IGraphicsAGG::DrawRotatedBitmap(), IGraphicsLice::DrawRotatedMask(), and IGraphicsAGG::DrawRotatedMask().
const WDL_String& IBitmap::GetResourceName () const inline
Returns
the resource name
Definition at line 129 of file IGraphicsStructs.h.
int IBitmap::H () const inline
Returns
overall bitmap height
Definition at line 101 of file IGraphicsStructs.h.
Referenced by IGraphicsNanoVG::DrawBitmap(), IGraphics::DrawBitmap(), IGraphicsCairo::DrawRotatedBitmap(), IGraphicsLice::DrawRotatedBitmap(), IGraphicsNanoVG::DrawRotatedBitmap(), IGraphicsAGG::DrawRotatedBitmap(), IGraphicsCairo::DrawRotatedMask(), IGraphicsLice::DrawRotatedMask(), and IGraphicsAGG::DrawRotatedMask().
int IBitmap::N () const inline
Returns
number of frames
Definition at line 113 of file IGraphicsStructs.h.
Referenced by IGraphics::DrawBitmap().
int IBitmap::W () const inline
Returns
overall bitmap width
Definition at line 97 of file IGraphicsStructs.h.
Referenced by IGraphicsNanoVG::DrawBitmap(), IGraphics::DrawBitmap(), IGraphicsCairo::DrawRotatedBitmap(), IGraphicsLice::DrawRotatedBitmap(), IGraphicsNanoVG::DrawRotatedBitmap(), IGraphicsAGG::DrawRotatedBitmap(), IGraphicsCairo::DrawRotatedMask(), IGraphicsLice::DrawRotatedMask(), and IGraphicsAGG::DrawRotatedMask().
The documentation for this class was generated from the following file:
IGraphicsStructs.h